### ISSUE TITLE
Consistency in ifs

### ISSUE THREAD

**Issue by broslukasz** [KrzysztofKazimierczak/pomodoro-counter#1]
https://github.com/KrzysztofKazimierczak/pomodoro-counter/blob/b5022debc2ad6f0113a3e1859c0f77a8a7f14049/main.js#L33

To have consistency with other ifs it is good to have this structure even if it is 3 lines
if () {

}

**Comment by KrzysztofKazimierczak** [comment]
I was taught this solution in case I only have one line of code. If this is a good practice that will help develop the code in the future, I will start writing this way.

**Comment by KrzysztofKazimierczak** [comment]
Is it good practice to write:
if (!this.active) {return};
instead:
if (!this.active) {
return
}
?
