### ISSUE TITLE
Descriptive functions

### ISSUE THREAD

**Issue by broslukasz** [KrzysztofKazimierczak/pomodoro-counter#2]
https://github.com/KrzysztofKazimierczak/pomodoro-counter/blob/08166bc360c3557425885bb47ba245a2c3fb19f5/main.js#L83-L90

It is good to have such logic closed in a private function with descriptive name of what the code does.

**Comment by KrzysztofKazimierczak** [comment]
I removed conditional operators with null on false, added private, common function for break and work changers. Is it better solution? In my opinion the code is more illegible than earlier.
