### ISSUE TITLE
Named logic of if condition

### ISSUE THREAD

**Issue by broslukasz** [KrzysztofKazimierczak/pomodoro-counter#3]
https://github.com/KrzysztofKazimierczak/pomodoro-counter/blob/0ea1965d9d812950ed1e756cce34809447ee54c3/main.js#L41

It is good to return the logic of if statement from function which name describes when this if happens; e.g.
if (theTimeValueseAreProper()) {
   iAmDoingALogic();
}

**Comment by KrzysztofKazimierczak** [comment]
I was taught this solution in case I only have one line of code. If this is a good practice that will help develop the code in the future, I will start writing this way.
