### ISSUE TITLE
Header instead of paragraph

### ISSUE THREAD

**Issue by broslukasz** [KrzysztofKazimierczak/pomodoro-counter#4]
https://github.com/KrzysztofKazimierczak/pomodoro-counter/blob/0ea1965d9d812950ed1e756cce34809447ee54c3/index.html#L23

Please check for rules of semantic html if any header h<number> fits more than paragraph here

**Comment by KrzysztofKazimierczak** [comment]
I forgot to change my temporary solution. Thank you for your attention. Changed
